INSERT INTO TODO(ID, NAME, DESCRIPTION, DATE, DONE)
VALUES (10001, 'Sourav', 'GET AWS CERTIFIED', CURRENT_DATE(), FALSE);
INSERT INTO TODO(ID, NAME, DESCRIPTION, DATE, DONE)
VALUES (10002, 'Sourav', 'GET GCP CERTIFIED', CURRENT_DATE(), FALSE);
INSERT INTO TODO(ID, NAME, DESCRIPTION, DATE, DONE)
VALUES (10003, 'Sourav', 'GET AZURE CERTIFIED', CURRENT_DATE(), FALSE);